# .streamlit/secrets.toml
#db접속:  로컬에서 "localhost"  도커에서 접속시 #"host.docker.internal"   ip고정할때 "192.168.112.1"  
[connections_dbms]
conn_name = "connections_mysql"

[connections_postgresql]
dialect = "postgresql"
host =    "host.docker.internal"  
port = 5432
database = "palette"
username = "hkcloud"
password = "hkcloud1"
encoding = 'UTF-8'

[connections_mysql]
dialect = "mysql"
host = "172.16.0.121"
port = 3306
database = "mysql"
username = "root"
password = "hkc!"
encoding = 'UTF-8'

